//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaSite.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.FileServiceSoap")]
    public interface FileServiceSoap {
        
        // CODEGEN: Generating message contract since element name fsBytes from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScanByFile", ReplyAction="*")]
        IdeaSite.ServiceReference.ScanByFileResponse ScanByFile(IdeaSite.ServiceReference.ScanByFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScanByFile", ReplyAction="*")]
        System.Threading.Tasks.Task<IdeaSite.ServiceReference.ScanByFileResponse> ScanByFileAsync(IdeaSite.ServiceReference.ScanByFileRequest request);
        
        // CODEGEN: Generating message contract since element name fsBytes from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScanByFileWithName", ReplyAction="*")]
        IdeaSite.ServiceReference.ScanByFileWithNameResponse ScanByFileWithName(IdeaSite.ServiceReference.ScanByFileWithNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScanByFileWithName", ReplyAction="*")]
        System.Threading.Tasks.Task<IdeaSite.ServiceReference.ScanByFileWithNameResponse> ScanByFileWithNameAsync(IdeaSite.ServiceReference.ScanByFileWithNameRequest request);
        
        // CODEGEN: Generating message contract since element name fsBytes from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScanByFileWithNameAndExtension", ReplyAction="*")]
        IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionResponse ScanByFileWithNameAndExtension(IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScanByFileWithNameAndExtension", ReplyAction="*")]
        System.Threading.Tasks.Task<IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionResponse> ScanByFileWithNameAndExtensionAsync(IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckFileByName", ReplyAction="*")]
        IdeaSite.ServiceReference.CheckFileByNameResponse CheckFileByName(IdeaSite.ServiceReference.CheckFileByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckFileByName", ReplyAction="*")]
        System.Threading.Tasks.Task<IdeaSite.ServiceReference.CheckFileByNameResponse> CheckFileByNameAsync(IdeaSite.ServiceReference.CheckFileByNameRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckFileByNameAndExtension", ReplyAction="*")]
        IdeaSite.ServiceReference.CheckFileByNameAndExtensionResponse CheckFileByNameAndExtension(IdeaSite.ServiceReference.CheckFileByNameAndExtensionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckFileByNameAndExtension", ReplyAction="*")]
        System.Threading.Tasks.Task<IdeaSite.ServiceReference.CheckFileByNameAndExtensionResponse> CheckFileByNameAndExtensionAsync(IdeaSite.ServiceReference.CheckFileByNameAndExtensionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScanByFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScanByFile", Namespace="http://tempuri.org/", Order=0)]
        public IdeaSite.ServiceReference.ScanByFileRequestBody Body;
        
        public ScanByFileRequest() {
        }
        
        public ScanByFileRequest(IdeaSite.ServiceReference.ScanByFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ScanByFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] fsBytes;
        
        public ScanByFileRequestBody() {
        }
        
        public ScanByFileRequestBody(byte[] fsBytes) {
            this.fsBytes = fsBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScanByFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScanByFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public IdeaSite.ServiceReference.ScanByFileResponseBody Body;
        
        public ScanByFileResponse() {
        }
        
        public ScanByFileResponse(IdeaSite.ServiceReference.ScanByFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ScanByFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ScanByFileResult;
        
        public ScanByFileResponseBody() {
        }
        
        public ScanByFileResponseBody(bool ScanByFileResult) {
            this.ScanByFileResult = ScanByFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScanByFileWithNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScanByFileWithName", Namespace="http://tempuri.org/", Order=0)]
        public IdeaSite.ServiceReference.ScanByFileWithNameRequestBody Body;
        
        public ScanByFileWithNameRequest() {
        }
        
        public ScanByFileWithNameRequest(IdeaSite.ServiceReference.ScanByFileWithNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ScanByFileWithNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] fsBytes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public ScanByFileWithNameRequestBody() {
        }
        
        public ScanByFileWithNameRequestBody(byte[] fsBytes, string name) {
            this.fsBytes = fsBytes;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScanByFileWithNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScanByFileWithNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public IdeaSite.ServiceReference.ScanByFileWithNameResponseBody Body;
        
        public ScanByFileWithNameResponse() {
        }
        
        public ScanByFileWithNameResponse(IdeaSite.ServiceReference.ScanByFileWithNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ScanByFileWithNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ScanByFileWithNameResult;
        
        public ScanByFileWithNameResponseBody() {
        }
        
        public ScanByFileWithNameResponseBody(bool ScanByFileWithNameResult) {
            this.ScanByFileWithNameResult = ScanByFileWithNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScanByFileWithNameAndExtensionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScanByFileWithNameAndExtension", Namespace="http://tempuri.org/", Order=0)]
        public IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionRequestBody Body;
        
        public ScanByFileWithNameAndExtensionRequest() {
        }
        
        public ScanByFileWithNameAndExtensionRequest(IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ScanByFileWithNameAndExtensionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] fsBytes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string extension;
        
        public ScanByFileWithNameAndExtensionRequestBody() {
        }
        
        public ScanByFileWithNameAndExtensionRequestBody(byte[] fsBytes, string name, string extension) {
            this.fsBytes = fsBytes;
            this.name = name;
            this.extension = extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScanByFileWithNameAndExtensionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScanByFileWithNameAndExtensionResponse", Namespace="http://tempuri.org/", Order=0)]
        public IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionResponseBody Body;
        
        public ScanByFileWithNameAndExtensionResponse() {
        }
        
        public ScanByFileWithNameAndExtensionResponse(IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ScanByFileWithNameAndExtensionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ScanByFileWithNameAndExtensionResult;
        
        public ScanByFileWithNameAndExtensionResponseBody() {
        }
        
        public ScanByFileWithNameAndExtensionResponseBody(bool ScanByFileWithNameAndExtensionResult) {
            this.ScanByFileWithNameAndExtensionResult = ScanByFileWithNameAndExtensionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckFileByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckFileByName", Namespace="http://tempuri.org/", Order=0)]
        public IdeaSite.ServiceReference.CheckFileByNameRequestBody Body;
        
        public CheckFileByNameRequest() {
        }
        
        public CheckFileByNameRequest(IdeaSite.ServiceReference.CheckFileByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckFileByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public CheckFileByNameRequestBody() {
        }
        
        public CheckFileByNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckFileByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckFileByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public IdeaSite.ServiceReference.CheckFileByNameResponseBody Body;
        
        public CheckFileByNameResponse() {
        }
        
        public CheckFileByNameResponse(IdeaSite.ServiceReference.CheckFileByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckFileByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckFileByNameResult;
        
        public CheckFileByNameResponseBody() {
        }
        
        public CheckFileByNameResponseBody(bool CheckFileByNameResult) {
            this.CheckFileByNameResult = CheckFileByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckFileByNameAndExtensionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckFileByNameAndExtension", Namespace="http://tempuri.org/", Order=0)]
        public IdeaSite.ServiceReference.CheckFileByNameAndExtensionRequestBody Body;
        
        public CheckFileByNameAndExtensionRequest() {
        }
        
        public CheckFileByNameAndExtensionRequest(IdeaSite.ServiceReference.CheckFileByNameAndExtensionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckFileByNameAndExtensionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string extension;
        
        public CheckFileByNameAndExtensionRequestBody() {
        }
        
        public CheckFileByNameAndExtensionRequestBody(string name, string extension) {
            this.name = name;
            this.extension = extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckFileByNameAndExtensionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckFileByNameAndExtensionResponse", Namespace="http://tempuri.org/", Order=0)]
        public IdeaSite.ServiceReference.CheckFileByNameAndExtensionResponseBody Body;
        
        public CheckFileByNameAndExtensionResponse() {
        }
        
        public CheckFileByNameAndExtensionResponse(IdeaSite.ServiceReference.CheckFileByNameAndExtensionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckFileByNameAndExtensionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckFileByNameAndExtensionResult;
        
        public CheckFileByNameAndExtensionResponseBody() {
        }
        
        public CheckFileByNameAndExtensionResponseBody(bool CheckFileByNameAndExtensionResult) {
            this.CheckFileByNameAndExtensionResult = CheckFileByNameAndExtensionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileServiceSoapChannel : IdeaSite.ServiceReference.FileServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServiceSoapClient : System.ServiceModel.ClientBase<IdeaSite.ServiceReference.FileServiceSoap>, IdeaSite.ServiceReference.FileServiceSoap {
        
        public FileServiceSoapClient() {
        }
        
        public FileServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdeaSite.ServiceReference.ScanByFileResponse IdeaSite.ServiceReference.FileServiceSoap.ScanByFile(IdeaSite.ServiceReference.ScanByFileRequest request) {
            return base.Channel.ScanByFile(request);
        }
        
        public bool ScanByFile(byte[] fsBytes) {
            IdeaSite.ServiceReference.ScanByFileRequest inValue = new IdeaSite.ServiceReference.ScanByFileRequest();
            inValue.Body = new IdeaSite.ServiceReference.ScanByFileRequestBody();
            inValue.Body.fsBytes = fsBytes;
            IdeaSite.ServiceReference.ScanByFileResponse retVal = ((IdeaSite.ServiceReference.FileServiceSoap)(this)).ScanByFile(inValue);
            return retVal.Body.ScanByFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdeaSite.ServiceReference.ScanByFileResponse> IdeaSite.ServiceReference.FileServiceSoap.ScanByFileAsync(IdeaSite.ServiceReference.ScanByFileRequest request) {
            return base.Channel.ScanByFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdeaSite.ServiceReference.ScanByFileResponse> ScanByFileAsync(byte[] fsBytes) {
            IdeaSite.ServiceReference.ScanByFileRequest inValue = new IdeaSite.ServiceReference.ScanByFileRequest();
            inValue.Body = new IdeaSite.ServiceReference.ScanByFileRequestBody();
            inValue.Body.fsBytes = fsBytes;
            return ((IdeaSite.ServiceReference.FileServiceSoap)(this)).ScanByFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdeaSite.ServiceReference.ScanByFileWithNameResponse IdeaSite.ServiceReference.FileServiceSoap.ScanByFileWithName(IdeaSite.ServiceReference.ScanByFileWithNameRequest request) {
            return base.Channel.ScanByFileWithName(request);
        }
        
        public bool ScanByFileWithName(byte[] fsBytes, string name) {
            IdeaSite.ServiceReference.ScanByFileWithNameRequest inValue = new IdeaSite.ServiceReference.ScanByFileWithNameRequest();
            inValue.Body = new IdeaSite.ServiceReference.ScanByFileWithNameRequestBody();
            inValue.Body.fsBytes = fsBytes;
            inValue.Body.name = name;
            IdeaSite.ServiceReference.ScanByFileWithNameResponse retVal = ((IdeaSite.ServiceReference.FileServiceSoap)(this)).ScanByFileWithName(inValue);
            return retVal.Body.ScanByFileWithNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdeaSite.ServiceReference.ScanByFileWithNameResponse> IdeaSite.ServiceReference.FileServiceSoap.ScanByFileWithNameAsync(IdeaSite.ServiceReference.ScanByFileWithNameRequest request) {
            return base.Channel.ScanByFileWithNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdeaSite.ServiceReference.ScanByFileWithNameResponse> ScanByFileWithNameAsync(byte[] fsBytes, string name) {
            IdeaSite.ServiceReference.ScanByFileWithNameRequest inValue = new IdeaSite.ServiceReference.ScanByFileWithNameRequest();
            inValue.Body = new IdeaSite.ServiceReference.ScanByFileWithNameRequestBody();
            inValue.Body.fsBytes = fsBytes;
            inValue.Body.name = name;
            return ((IdeaSite.ServiceReference.FileServiceSoap)(this)).ScanByFileWithNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionResponse IdeaSite.ServiceReference.FileServiceSoap.ScanByFileWithNameAndExtension(IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionRequest request) {
            return base.Channel.ScanByFileWithNameAndExtension(request);
        }
        
        public bool ScanByFileWithNameAndExtension(byte[] fsBytes, string name, string extension) {
            IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionRequest inValue = new IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionRequest();
            inValue.Body = new IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionRequestBody();
            inValue.Body.fsBytes = fsBytes;
            inValue.Body.name = name;
            inValue.Body.extension = extension;
            IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionResponse retVal = ((IdeaSite.ServiceReference.FileServiceSoap)(this)).ScanByFileWithNameAndExtension(inValue);
            return retVal.Body.ScanByFileWithNameAndExtensionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionResponse> IdeaSite.ServiceReference.FileServiceSoap.ScanByFileWithNameAndExtensionAsync(IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionRequest request) {
            return base.Channel.ScanByFileWithNameAndExtensionAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionResponse> ScanByFileWithNameAndExtensionAsync(byte[] fsBytes, string name, string extension) {
            IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionRequest inValue = new IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionRequest();
            inValue.Body = new IdeaSite.ServiceReference.ScanByFileWithNameAndExtensionRequestBody();
            inValue.Body.fsBytes = fsBytes;
            inValue.Body.name = name;
            inValue.Body.extension = extension;
            return ((IdeaSite.ServiceReference.FileServiceSoap)(this)).ScanByFileWithNameAndExtensionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdeaSite.ServiceReference.CheckFileByNameResponse IdeaSite.ServiceReference.FileServiceSoap.CheckFileByName(IdeaSite.ServiceReference.CheckFileByNameRequest request) {
            return base.Channel.CheckFileByName(request);
        }
        
        public bool CheckFileByName(string name) {
            IdeaSite.ServiceReference.CheckFileByNameRequest inValue = new IdeaSite.ServiceReference.CheckFileByNameRequest();
            inValue.Body = new IdeaSite.ServiceReference.CheckFileByNameRequestBody();
            inValue.Body.name = name;
            IdeaSite.ServiceReference.CheckFileByNameResponse retVal = ((IdeaSite.ServiceReference.FileServiceSoap)(this)).CheckFileByName(inValue);
            return retVal.Body.CheckFileByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdeaSite.ServiceReference.CheckFileByNameResponse> IdeaSite.ServiceReference.FileServiceSoap.CheckFileByNameAsync(IdeaSite.ServiceReference.CheckFileByNameRequest request) {
            return base.Channel.CheckFileByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdeaSite.ServiceReference.CheckFileByNameResponse> CheckFileByNameAsync(string name) {
            IdeaSite.ServiceReference.CheckFileByNameRequest inValue = new IdeaSite.ServiceReference.CheckFileByNameRequest();
            inValue.Body = new IdeaSite.ServiceReference.CheckFileByNameRequestBody();
            inValue.Body.name = name;
            return ((IdeaSite.ServiceReference.FileServiceSoap)(this)).CheckFileByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdeaSite.ServiceReference.CheckFileByNameAndExtensionResponse IdeaSite.ServiceReference.FileServiceSoap.CheckFileByNameAndExtension(IdeaSite.ServiceReference.CheckFileByNameAndExtensionRequest request) {
            return base.Channel.CheckFileByNameAndExtension(request);
        }
        
        public bool CheckFileByNameAndExtension(string name, string extension) {
            IdeaSite.ServiceReference.CheckFileByNameAndExtensionRequest inValue = new IdeaSite.ServiceReference.CheckFileByNameAndExtensionRequest();
            inValue.Body = new IdeaSite.ServiceReference.CheckFileByNameAndExtensionRequestBody();
            inValue.Body.name = name;
            inValue.Body.extension = extension;
            IdeaSite.ServiceReference.CheckFileByNameAndExtensionResponse retVal = ((IdeaSite.ServiceReference.FileServiceSoap)(this)).CheckFileByNameAndExtension(inValue);
            return retVal.Body.CheckFileByNameAndExtensionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdeaSite.ServiceReference.CheckFileByNameAndExtensionResponse> IdeaSite.ServiceReference.FileServiceSoap.CheckFileByNameAndExtensionAsync(IdeaSite.ServiceReference.CheckFileByNameAndExtensionRequest request) {
            return base.Channel.CheckFileByNameAndExtensionAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdeaSite.ServiceReference.CheckFileByNameAndExtensionResponse> CheckFileByNameAndExtensionAsync(string name, string extension) {
            IdeaSite.ServiceReference.CheckFileByNameAndExtensionRequest inValue = new IdeaSite.ServiceReference.CheckFileByNameAndExtensionRequest();
            inValue.Body = new IdeaSite.ServiceReference.CheckFileByNameAndExtensionRequestBody();
            inValue.Body.name = name;
            inValue.Body.extension = extension;
            return ((IdeaSite.ServiceReference.FileServiceSoap)(this)).CheckFileByNameAndExtensionAsync(inValue);
        }
    }
}
